name: Go Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Go Test And Build
    runs-on: ubuntu-latest
    steps:

      - name: load Go 1.17 env
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: checkout
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod tidy

      - name: Test
        run: |
          go test -v ./...
